export enum ActionType {
  GET_PERSON_REQUEST = 'GET_PERSON_REQUEST',
  GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS',
  GET_PERSON_ERROR = 'GET_PERSON_ERROR',

  UPDATE_PERSON_REQUEST = 'UPDATE_PERSON_REQUEST',
  UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS',
  UPDATE_PERSON_ERROR = 'UPDATE_PERSON_ERROR',

  GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST',
  GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS',
  GET_ADDRESS_ERROR = 'GET_ADDRESS_ERROR',

  GET_VERIFICATION_REQUEST = 'GET_VERIFICATION_REQUEST',
  GET_VERIFICATION_SUCCESS = 'GET_VERIFICATION_SUCCESS',
  GET_VERIFICATION_ERROR = 'GET_VERIFICATION_ERROR',
}